### ISSUE TITLE
Improve message from dup analyzer

### ISSUE THREAD

**Issue by smacker** [src-d/lookout-gometalint-analyzer#7]
Example of comment from dupl analyzer: https://github.com/src-d/lookout/pull/224#discussion_r215352817

> duplicate of /tmp/gometalint178171015/provider___.github.___poster_test.go:141-164 (dupl)

Todo:
1. remove prefix of temporary directory (most probably the easiest way is to preprocess all output removing tmp dir string. It's quite unique)
2. change artificialSep so it wouldn't be displayed as markdown. Or just create directories instead. Or change separator back to "/" before posting.

**Comment by bzz** [comment]
Thank you for filing this!

Indeed:
 - prefix not removed => it's definitely a bug
 - we run all file-level analysis together in a single run, so I belive it needs to have all files in a single directory to do so

The expected behaviour is - file path should be reconstructed back to original one, before reporting

**Comment by smacker** [comment]
> we run all file-level analysis together in a single run, so I belive it needs to have all files in a single directory to do so

what is the problem with `gometalinter.v2 <tmp-path>/...`?
